"""Quantity type

Revision ID: 4589b30a2334
Revises: a38078c2ff73
Create Date: 2019-12-24 07:53:36.532053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4589b30a2334'
down_revision = 'a38078c2ff73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('quantity_type', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'quantity_type')
    # ### end Alembic commands ###
