"""empty message

Revision ID: 9f69e4fdb7c7
Revises: cb14c25e3f2e
Create Date: 2020-01-25 10:03:30.569842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f69e4fdb7c7'
down_revision = 'cb14c25e3f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'amount')
    # ### end Alembic commands ###
